services:
  db:
    image: postgres:16-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: zeno
      POSTGRES_PASSWORD: zeno_dev
      POSTGRES_DB: zeno
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
